[Citizen]
startingLevel = 10
baseHealth = 150
baseMana = 0
baseCapacity = 400
premium = false
vocation = 0
sex = "male"
towns = [1, 2, 3]
outfit = {id = 128, head = 1, body = 1, legs = 1, feet = 1, mount = 0}
skills = {unarmed = 1, twohand = 1, onehand = 1, shield = 1, fishing = 1}

[Resident]
startingLevel = 1
baseHealth = 150
baseMana = 0
baseCapacity = 400
premium = false
vocation = 0
sex = "female"
towns = [1, 2, 3]
outfit = {id = 136, head = 1, body = 1, legs = 1, feet = 1, mount = 0}
skills = {unarmed = 1, twohand = 1, onehand = 1, shield = 1, fishing = 1}